name: Build and Test

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-build:
    name: Test & Build (${{ matrix.os }} ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
          - os: darwin
            arch: arm64
            runner: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o chromium-list-${{ matrix.os }}-${{ matrix.arch }} .

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: chromium-list-${{ matrix.os }}-${{ matrix.arch }}
        path: chromium-list-${{ matrix.os }}-${{ matrix.arch }}
